### ISSUE TITLE
Buttons on the Top Bar (i.e. options) including delete, move ,copy,rename and sort are not working after the Latest Commit

### ISSUE THREAD

**Issue by HackStyx** [HackStyx/DataFlow-File-Manager#1]
**Describe the bug**
Buttons on the Top Bar (i.e. options) including delete, move ,copy,rename and sort are not working after the Latest Commit
**To Reproduce**
1. Run the Python File 
2. Click on any File
3. Select any option on the Top Bar
4. See the error

**Expected behavior**
After Selecting the options, It should work as it is named and should not be crashing.

**Desktop :**
 - OS: Windows 11
 - Python Version : Latest
 - Vs Code version : latest 

**Additional context**
After selecting Sort by Time option, It get crashed

**Comment by Sagewiiz** [comment]
Assign me this

**Comment by HackStyx** [comment]
Done 👍
